linux_display_server x11
wayland_titlebar_color background
hide_window_decorations no
background_opacity 0.8
font_family JetBrainsMono Nerd Font
font_size 11
resize_in_steps yes
cursor_blink_interval 0

# Tokyonight by folke
include colors.conf
