# config_directory/config.toml
[config]
reload_apps = false
set_wallpaper = false
prefix = '@'

[config.reload_apps_list]
waybar = false
kitty = false
gtk_theme = false
dunst = false


[config.colors_to_harmonize]
red = "#cc0000"
orange = "#fe8019"
yellow = "#c4a000"
green = "#4e9a06"
blue = "#729fcf"
cyan = "#06989a"
magenta = "#75507b"
# red = "#f7768e"
# green = "#9ece6a"
# yellow = "#e0af68"
# blue = "#7aa2f7"
# magenta = "#bb9af7"
# cyan = "#7dcfff"
white = "#d3d7cf"
white2 = "#ffffff"
# color1 = "#f7768e"
# color2 = "#9ece6a"
# color3 = "#e0af68"
# color4 = "#7aa2f7"
# color5 = "#bb9af7"
# color6 = "#7dcfff"
# color7 = "#a9b1d6"
# color8 = "#414868"
# color9 = "#f7768e"
# color10 = "#9ece6a"
# color11 = "#e0af68"
# color12 = "#7aa2f7"
# color13 = "#bb9af7"
# color14 = "#7dcfff"
# color15 = "#c0caf5"
# color16 = "#ff9e64"
# color17 = "#db4b4b"

[templates] # Another way
test2 = { input_path = '~/.config/matugen/templates/ags.scss.template', output_path = '~/.config/matugen/templates/ags.scss' }
