[colors.primary]
background = "#161217"
foreground = "#e9e0e7"


[colors.normal]
black = "#161217"
red = "#c90044"
green = "#7c9200"
yellow = "#d89704"
blue = "#819bd3"
magenta = "#73507c"
cyan = "#1396aa"
white = "#d2d7d1"

[colors.bright]
black = "#3d373d"
red = "#c90044"
green = "#7c9200"
yellow = "#d89704"
blue = "#819bd3"
magenta = "#73507c"
cyan = "#1396aa"
white = "#ffffff"
