[colors.primary]
background = "#1a1110"
foreground = "#f1dedc"


[colors.normal]
black = "#1a1110"
red = "#cc0003"
green = "#7c9200"
yellow = "#d89704"
blue = "#819bd3"
magenta = "#7d4e70"
cyan = "#1d9988"
white = "#d5d7cd"

[colors.bright]
black = "#423735"
red = "#cc0003"
green = "#7c9200"
yellow = "#d89704"
blue = "#819bd3"
magenta = "#7d4e70"
cyan = "#1d9988"
white = "#ffffff"
