[colors.primary]
background = "#fff8f6"
foreground = "#3a0b01"

[colors.normal]
black = "#f1dfda"
white = "#3a0b01"
red = "#c32400"
green = "#7c9200"
yellow = "#d89704"
blue = "#819bd3"
magenta = "#7d4e70"
cyan = "#1d9988"

[colors.bright]
black = "#ffdbd1"
white = "#723523"
red = "#c32400"
green = "#7c9200"
yellow = "#d89704"
blue = "#819bd3"
magenta = "#7d4e70"
cyan = "#1d9988"

