[colors.primary]
background = "#1a110f"
foreground = "#f1dfda"

[colors.normal]
black = "#1a110f"
white = "#d5d7cd"
red = "#c32400"
green = "#7c9200"
yellow = "#d89704"
blue = "#819bd3"
magenta = "#7d4e70"
cyan = "#1d9988"

[colors.bright]
black = "#423734"
white = "#ffffff"
red = "#c32400"
green = "#7c9200"
yellow = "#d89704"
blue = "#819bd3"
magenta = "#7d4e70"
cyan = "#1d9988"

